-- MySQL Script generated by MySQL Workbench
-- Mon Jan 19 08:40:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema COMERCIO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `PROVEEDORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROVEEDORES` (
  `CIFprov` CHAR(9) NOT NULL,
  `nombreprov` VARCHAR(30) NULL,
  `direccion` VARCHAR(100) NULL,
  `nacionalidad` VARCHAR(30) NULL,
  `representante` VARCHAR(30) NULL,
  `email` VARCHAR(100) NULL,
  `telefono` VARCHAR(9) NULL,
  PRIMARY KEY (`CIFprov`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRODUCTOS` (
  `id_producto` INT NOT NULL,
  `nombreproducto` VARCHAR(30) NULL,
  `descripcion` VARCHAR(100) NULL,
  `precio` FLOAT NULL,
  `stock` INT NULL,
  `foto` VARCHAR(100) NULL,
  `pais` VARCHAR(30) NULL,
  `CIF` CHAR(9) NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `CIF_idx` (`CIF` ASC) ,
  CONSTRAINT `CIF`
    FOREIGN KEY (`CIF`)
    REFERENCES `PROVEEDORES` (`CIFprov`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `PROVEEDORES`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `PROVEEDORES` (`CIFprov`, `nombreprov`, `direccion`, `nacionalidad`, `representante`, `email`, `telefono`) VALUES ('A12121212', 'Zara', 'C/ Luz 5', 'España', 'A. Pérez', 'aperez@mail.com', '612121212');
INSERT INTO `PROVEEDORES` (`CIFprov`, `nombreprov`, `direccion`, `nacionalidad`, `representante`, `email`, `telefono`) VALUES ('B34343434', 'Mercadona', 'C/ Luna 3', 'España', 'C. García', 'cgarcia@mail.com', '634343434');
INSERT INTO `PROVEEDORES` (`CIFprov`, `nombreprov`, `direccion`, `nacionalidad`, `representante`, `email`, `telefono`) VALUES ('C56565656', 'Carrefour', 'C/ Sol 1', 'España', 'J. Sánchez', 'jsanchez@mail.com', '656565656');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PRODUCTOS`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `PRODUCTOS` (`id_producto`, `nombreproducto`, `descripcion`, `precio`, `stock`, `foto`, `pais`, `CIF`) VALUES (1, 'Procesadores i5', 'Procesadores intel i5', 90, 50, 'i5.png', 'Corea', 'A12121212');
INSERT INTO `PRODUCTOS` (`id_producto`, `nombreproducto`, `descripcion`, `precio`, `stock`, `foto`, `pais`, `CIF`) VALUES (2, 'Disco SSD 1T Kinstong', 'Disco duro 1T Kinstong', 80, 100, 'ssd-K1.png', 'España', 'B34343434');
INSERT INTO `PRODUCTOS` (`id_producto`, `nombreproducto`, `descripcion`, `precio`, `stock`, `foto`, `pais`, `CIF`) VALUES (3, 'Procesador Rizen 7', 'Procesador AMD Rizen 7', 150, 90, 'rizen7.png', 'China', 'B34343434');
INSERT INTO `PRODUCTOS` (`id_producto`, `nombreproducto`, `descripcion`, `precio`, `stock`, `foto`, `pais`, `CIF`) VALUES (4, 'Rartón logitech cable', 'Ratón óptico con cable', 7, 100, 'ratonlogitech.png', 'Japón', 'A12121212');
INSERT INTO `PRODUCTOS` (`id_producto`, `nombreproducto`, `descripcion`, `precio`, `stock`, `foto`, `pais`, `CIF`) VALUES (5, 'Impresora Laserjet M209d', 'Impresora láser monocromo para oficina', 90, 10, 'impresora.jpg', 'Japón', 'C56565656');

COMMIT;

